spring.application.name=processing-server

server.port=8022
processing.batch.size = 50
# db settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/applications_students
spring.datasource.username=administrator
spring.datasource.password=administrator

# flyway settings
spring.flyway.url=jdbc:postgresql://localhost:5432/applications_students
spring.flyway.user=administrator
spring.flyway.password=administrator
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
